### ISSUE TITLE
Setting starOn and starOff doesn't work

### ISSUE THREAD

**Issue by willc0de4food** [bmc/jquery-raty-rails#8]
When I set the options for starOn and starOff, the path is being pre-empted with "/assets/jquery.raty/". For example, the follow code:
`starOff: '<%= asset_path("star-white.png") %>',
starOn: '<%= asset_path("star-black.png") %>',`

Produces this HTML:
`<img src="/assets/jquery.raty//assets/star-black-72edb06395365114a5c51126180a26189e96b88eb29c23a662ec0dd187e650c0.png" alt="1" title="good">`

**Comment by willc0de4food** [comment]
Figured it out after looking at some of the other open issues. I added `path: ''` to the options, and the images are displaying correctly now.

**Comment by bmc** [comment]
A former colleague referred to this phenomenon (don't get around to responding, and the person comes back later and says, "Never mind; I solved it") with: "Another problem successfully aged."

Glad you found it.
